### ISSUE TITLE
Working simple ICO page for Fushuma ICO

### ISSUE THREAD

**Issue by creepas** [Fushuma/Dev_grants#1]
# Grant Proposal: Basic ICO Webpage prototype with Countdown

For the first grant we open ICO webpage with countdown. Please submit your budget request.

**Project Title:**
- ICO Webpage 

**Applicant Information:**
- **Name:** [Applicant's Name]
- **Contact Email:** [Applicant's Email]
- **GitHub or relevant online profiles:** [GitHub Profile/Portfolio]
- **Team Members (if applicable):** [List team members]

**Project Overview:**
- **Summary:** Develop a basic Initial Coin Offering (ICO) webpage featuring a countdown timer to the launch date.
- **Goals:** Create a visually appealing webpage that effectively communicates the ICO's value proposition and launch timeline.
- **Impact:** Enhance brand visibility and user engagement for the ICO.

**Technical Details:**
- **Technology stack:** HTML, CSS, JavaScript (for the countdown timer)
- **Project roadmap:** Design phase -> Development phase -> Testing -> Launch
- **Current state:** Conceptualization

**Funding (example only):**
- **Total amount requested:** $X
- **Budget breakdown:** $Y for webpage development
- **Payment address:** [Cryptocurrency Address]

**Additional Information:**
- **Previous work:** [Links to previous design projects]
- **How did you hear about our grants program?:** [Source]

**Declaration:**
I declare that the information provided is accurate to the best of my knowledge.

- [Applicant's Name]
- [Date]

---

Submit this application by replying.

**Comment by 1rmsnatch** [comment]
Hi, I can do this for you. I am web developer with front end (HTML, CSS, JS) and backend (Apache, PHP) experiences. I would suggest to use some premium HTML template - for example this one: https://demo.ovathemes.com/cryptlight_html/cryplight/index-6.html
What dou you think about it?

**Comment by creepas** [comment]
How much you want for deployment?

**Comment by 1rmsnatch** [comment]
> How much you want for deployment?

I work for 50 USD/ hour. This project could be somewhere from 20 to 100 hours, depending on your requirements. 

We can start almost immediately.

**Comment by creepas** [comment]
Sure start. And i will create telegram chat cReepass.

**Comment by wink2w** [comment]
I can work for $40/hr.
I am sure that I will complete it from 20 hrs to 40 hrs.

**Comment by creepas** [comment]
> I can work for $40/hr. I am sure that I will complete it from 20 hrs to 40 hrs.

Can you post some "links" to your work? Or send me to telegram.

cReepas

**Comment by Dalcor** [comment]
Hi, I can do it, I have experience in web3 development and I have successful case of ICO page developing.

It will be ready in two weeks. ICO page will include multiple networks and wallets, design mockups and mobile version from the box.

**Comment by spatialiste** [comment]
Hello, all.

We have completed the ICO page structure. You can see it [**here**](https://docs.google.com/document/d/1y596yBZrpZjM5hBmPltkv__LPNzv-W1HJDKyNdHJvJs/edit). This page can be based on the [**template**](https://demo.ovathemes.com/cryptlight_html/cryplight/index-6.html) proposed by @1rmsnatch or similar.

The page will have three images and two animations, and I will open a specific grant for that.

Please propose the cost of building this page and the expected deadline.

**Comment by PrinceKAlgorithmXpert** [comment]
I can completed from 8 hrs to 10 hrs. (my rate is $40/hr)
i will complete it till 4/30

**Comment by 1rmsnatch** [comment]
Hi, I can complete it with this template in about 10 - 15 hours this week.

**Comment by creepas** [comment]
Hello, pls complete the page.

Thank you

**Comment by 1rmsnatch** [comment]
Hi, second draft is here: https://github.com/Fushuma/ICO/tree/second-draft
I am expecting some feedback as this is just a draft.
Currently I spent 5 hours with a first draft and 6 hours with a second draft.

**Comment by spatialiste** [comment]
Hello @1rmsnatch,

Thank you, we will review it and get back to you.

Regarding the budget, I would like to ensure that we are on the same page. As per the discussion on this thread, this ICO page can be completed in 10 hours, with prices ranging from 400 USD to 750 USD. Therefore, we have decided to not allocate more than 600 USD for this grant.

Also, I updated the [ICO page description](https://docs.google.com/document/d/1y596yBZrpZjM5hBmPltkv__LPNzv-W1HJDKyNdHJvJs/edit) with the pictures that have been finalized, and put their links in purple.

**Comment by 1rmsnatch** [comment]
Unfortunately, I am unable to open any of your images. Could you please check if there's an issue?

[Image #1: Stylized floating Fushuma logo.]
[Image: #2 Airdrops from Funded Projects.]
[[Image #3: Tokenomics.]

I would say that it´s saved on private github repository

**Comment by spatialiste** [comment]
> Unfortunately, I am unable to open any of your images. Could you please check if there's an issue?
> 
> [Image #1: Stylized floating Fushuma logo.] [Image: #2 Airdrops from Funded Projects.] [[Image #3: Tokenomics.]
> 
> I would say that it´s saved on private github repository

Hello, OK I'm sorry for that, let me post the images directly.

### Stylized floating Fushuma logo.

![313427583-aae6b5c0-9e01-4d21-9686-94d207a5bfd8](https://github.com/Fushuma/Dev_grants/assets/41175366/23d1649f-4191-4b2b-a94b-525e3cdd6e6e)


### Airdrops from Funded Projects.
![Airdrop-dragon 02](https://github.com/Fushuma/Dev_grants/assets/41175366/81fb6b50-cbb9-44e8-9362-c75745ba110a)

### Tokenomics.
![Tokenomic_02](https://github.com/Fushuma/Dev_grants/assets/41175366/5f39c956-db47-4a36-8528-a30779c0ccff)

**Comment by 1rmsnatch** [comment]
I pushed page with images to the repository.

Do you really want logo on the white background? If not I need this image on transparent background.

**Comment by 1rmsnatch** [comment]
@spatialiste Hi, how is it going? Do you have any comments? Do you want to talk about it? 
As I mentioned earlier - we need your logo on transparent background.

**Comment by spatialiste** [comment]
Hello everyone,

After discussing with the team, we have decided to simplify our approach by not creating a separate ICO page. Since the launch of the Fushuma website we have a clear vision of the Fushuma style, which differs from the initial template for the ICO page. Therefore, it makes more sense to conduct the sale via the Launchpad page.

Launchpad Grant Link: [Launchpad Grant](https://github.com/Fushuma/Dev_grants/issues/4)

In recognition of the efforts made by @1rmsnatch, we are allocating an exceptional reward of 300 USDT, which corresponds to 50% of the budget initially allocated.

Please @1rmsnatch provide me with your BEP20 wallet and we will proceed with the payment as soon as possible.

Thank you for your understanding and continued support.

**Comment by 1rmsnatch** [comment]
Hi, thanks for letting me know. 
My address is 0xc27a9C069D88B8f08EF9FDF75df18D1c55d4358e

**Comment by spatialiste** [comment]
Hey @1rmsnatch, the payment has been processed, please find the transaction link below:

https://bscscan.com/tx/0xf341b37711e9b846e3542fca86cc327ceee505ca0eef511e8274a3414494b89f.

This grant is now closed, thanks again for your support.
