### ISSUE TITLE
Fushuma Website Creation Grant

### ISSUE THREAD

**Issue by spatialiste** [Fushuma/Dev_grants#11]
Fushuma aims to be a decentralized blockchain ecosystem with transparency in each aspect. To achieve this, we are launching a grant to create the Fushuma website. 

The website will be built on WordPress and the Fushuma team will supervise the development. 

# Grant Details
- **Platform:** WordPress.
- **Supervision:** The website development will be conducted under the supervision of the Fushuma team.
- **Communication:** Discussions with the Fushuma team will be conducted via Telegram due to time constraints.
- **Transparency:** A progress update will be posted weekly on the current GitHub repository for transparency.
- **Deadline:** The project is expected to be completed by June 7th, 2024.
### Website Structure
**1. Home Page**
   - **Header:** Navigation menu, Fushuma logo, and a Call-To-Action (CTA) button.
   - **Hero Section:** Banner with a brief tagline about Fushuma.
   - **Key Features:** Brief highlight of the core features.
   - **Latest News:** The latest news or announcements related to Fushuma. (Optional).
   - **Call to Action:** Invite visitors to join the community.
   
**2. About Us Page**
   - **Mission:** Fushuma’s mission and vision.
   - **Team:** Core team members with brief bios and photos.
   - **History:** Briefly explain the journey from Callisto Network to Fushuma.
   - **Values:** Highlight Fushuma’s core values.
   
**3. Ecosystem Page**
   - **Partners:** Showcase strategic partners and collaborations.
   - **Projects:** Highlight projects and dApps built on Fushuma.
   - **Grants and Funding:** Information about available grants, funding opportunities, and how to apply.
   
**4. Blog Section**
   - **Articles:** Blog posts about Fushuma.
   - **Announcements:** Updates and announcements.
   - **Community Contributions:** Articles and content from community members.
   
**5. Contact Us**
   - **Contact Form:** Simple form for inquiries and support requests.
   - **Email:** Direct email address for queries.
   - **Social Media Links:** Links to Fushuma's social media profiles.
   
**6. Footer**
   - **Quick Links:** Links to important pages like Home, About Us, Ecosystem, Blog, and Contact Us.
   - **Social Media Icons:** Icons linking to social media profiles.
   
### Evaluation KPIs
- High-speed loading.
- Responsive design.
- Seamless user interaction.

# Example of Submission
   - **Project completion:** June 7th, 2024.
   - **Budget:** Specify the total amount requested for the development.
   - **Bonus:** You will receive a 20 percent bonus in FUMA coin, to be distributed 7 days after the beginning of trading on Sloth Finance.
   - **Payment Address:** Provide the cryptocurrency address for receiving funds (BEP20).

**Comment by ERROR-SYS** [comment]
Hello, I would like to participate in this grant but the time given is relatively short. I am committed to delivering a high-quality website within the required period. Below is my offer:

**Landing Page:** Create a landing page that adheres to the Fushuma design and color scheme. Detailed instructions and collaboration will be required to ensure alignment with your vision.
- _Estimated cost:_ $700 to $900 (depending on complexity).

**Web Pages:**
   - Contact Us Page: Includes a contact form.
     - _Estimated cost:_ $300 to $450.
   - About Us Page:
     - _Estimated cost:_ $150 to $200.
   - Ecosystem Page: 
     - _Estimated cost:_ $150 to $200.
   - Header and Footer: Creation of a header and footer with menus and media links.

**Blog Setup:** Creation of a blog section and a template for typical blog posts.
   - _Estimated cost:_ $350 (depending on requirements and complexity).

**Additional Services:**
   - Installation and configuration of necessary plugins.
   - Website security and optimization.
   - Comprehensive testing to ensure speed and responsiveness across devices.

Please note that costs are estimates and the final price may vary based on specific project requirements and complexities. I am confident in my ability to deliver a website that meets your expectations within the given timeframe. I can start working immediately upon approval.

**Comment by spatialiste** [comment]
@ErrSystem thank you for applying.

For that Grant, we have a budget of 1900 USD, and we will request that you maintain the website for 45 days while we ensure everything works as expected.

If these conditions suit you, please contact me on Telegram (https://t.me/TontonBenz) so we can start working.

**Comment by ERROR-SYS** [comment]
Ok done, I will contact you.

**Comment by ERROR-SYS** [comment]
Hello, Here is an update on what you requested, tasks in progress will be completed Monday morning.

### Completed:

- ✅ Landing Page:

   - Highlights the three key points of Fushuma: Transparency, Decentralization and its community-driven system. 
   - Latest posts and developer grants.
   - The Fushuma animated logo is being prepared by Fushuma.   
   
- ✅ Dojo (Blog Section):

   - Articles & Announcements: Regrouped under "Publications".
   - Added Video Blogs and Community Contributions sections.
   - Includes the latest developer grants.
  
- ✅ Blueprint.

- ✅ Fuma Tokenomics: Creation of the page and optimization.

- ✅ Contact Us:

   - Contact Form: Simple form for inquiries and support requests.
   - Direct email address for queries.
   - Links to Fushuma's social media profiles.

- ✅ Header:

   - Contains the logo and links to important pages.
   - The landing page and the dojo are split into sections that users can access directly from the menu.
   - About entry is devised into Rise of the decentralization, Blueprint and About Fushuma.

- ✅ Footer:

   - Includes the logo and various links.
   - Quick Links: Links to sections from the landing page.
   - Resources: Links to special pages like Fuma Tokenomics and Contact Us.
   - Social medias.

- ✅ 404 and Coming Soon Pages:

   - Suggest some pages that might be useful to the users.
   
- ✅ Templates for blog posts and video blog posts have been created on the demand of TonTon.
   
- Various:

   - ✅ Google Analytics setup.
   - ✅ Activity log setup and various security settings.
   - ✅  Installation and configuration of WPoptimize premium for one year.
   
###    In Progress:

- 👨‍💻 About Fushuma:

   - Describes the goals of Fushuma.
   - Includes sections about the team members and some of their achievements in the past.
   
- 👨‍💻 FAQs Page.

- 👨‍💻 Responsive.

**Comment by ERROR-SYS** [comment]
Hello, the website was delivered yesterday morning, I fixed all the issues discovered and reported by the team. As in our agreement I will maintain the website for 45 days. Here is a list of what I've done so far:

- ✅ Landing Page:

   - Highlights the three key points of Fushuma: Transparency, Decentralization and its community-driven system.
Latest posts and developer grants.

- ✅ Dojo (Blog Section):

  - Articles & Announcements: Regrouped under "Publications".
  - Added Video Blogs and Community Contributions sections (Video Blogs are disabled for the moment).
  - Includes the latest developer grants.

- ✅ Blueprint.

- ✅ Fuma Tokenomics: Creation of the page and optimization.

- ✅ Contact Us:

   - Contact Form: Simple form for inquiries and support requests.
   - Direct email address for queries.
   - Links to Fushuma's social media profiles.

- ✅ Header:

   - Contains the logo and links to important pages.
   - The landing page and the dojo are split into sections that users can access directly from the menu.
   - About entry is devised into Rise of the decentralization, Blueprint and About Fushuma.

- ✅ Footer:

  - Includes the logo and various links.
  - Quick Links: Links to sections from the landing page.
  - Resources: Links to special pages like Fuma Tokenomics and Contact Us.
  - Social medias.

- ✅ 404 and Coming Soon Pages:

  - Suggest some pages that might be useful to the users.

- ✅ Templates for blog posts and video blog posts have been created on the demand of TonTon.

- Various:

  - ✅ Google Analytics setup.
  - ✅ Activity log setup and various security settings.
  - ✅ Installation and configuration of WPoptimize premium for one year.

- ✅ About Fushuma:

  - Describes the goals of Fushuma.
  - Includes sections about the team members and some of their achievements in the past.
 
- ✅ FAQs Page: waiting for entries from the team.

- ✅ Responsive.


- Here is the wallet address where you can process the payment: 0x28544a8e2cdd21f58479628caf41da3b1884acb9

**Comment by spatialiste** [comment]
Hello, thank you. We are currently reviewing the website. Please allow us a few days, and I will get back to you.

Thanks again for your effort in delivering the website in such a short time.

**Comment by spatialiste** [comment]
Hey @ErrSystem, we checked the website and it looks great! I'm happy to say that we've processed the payment. Thanks for being so quick!

https://bscscan.com/tx/0xaad96bd2ef548c63109e35cba19272eb5d436de607eccccbb98e0c1e0a310242

This grant is now closed.
