### ISSUE TITLE
Fushuma Website Pictures #1

### ISSUE THREAD

**Issue by spatialiste** [Fushuma/Dev_grants#12]
# Designer Grants Application

Fushuma is looking for talented and imaginative designers to create engaging images in the Fushuma style for our website.
The idea is to let designers propose their vision of Fushuma and the proposed themes. The descriptions are concise on purpose.

- **Image 1:**  Fushuma On-chain Democracy

An image representing/symbolizing the Fushuma governance model with, for example, the community members.

- **Image 2:** Rise Of Democracy

This image should represent the renewal in a powerful and inspiring manner. 

----
**EDIT**

- **Image 3:** Fushuma Dojo

In traditional Japan, Dojo is a place of learning and practice.

----

### Design Style Guide:
For both items, we are looking for designs in a Japanese old style— clean, and 2D. Technical representations are to be avoided, and symbolism is appreciated.

### Below are some Fushuma images for your reference:

**The Fushuma Logo**

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/57f06cf5-de2c-40a7-b9f2-266262619d36)

**The Fushuma Announcement Banner**

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/488f2426-9edd-451d-83f5-aca090ea879b)

**The Fushuma Twitter Banner**
![image](https://github.com/Fushuma/Dev_grants/assets/41175366/92c45db4-fc9a-45d6-8264-029f44f3ebd2)

**ICO Pages Images**
![image](https://github.com/Fushuma/Dev_grants/assets/41175366/7c541aec-7912-4226-82cd-ef3f53400da3)

-----
### Application Submission Requirements:
- **Proposed Timeline:** [The time you need to complete these designs]
- **Total amount requested:** [Amount in USDT]
- **Payment address:** [Cryptocurrency address for receiving funds]

**Comment by WhyNt2024** [comment]
I am submitting two images for the grant. I used the same watercolor style to make the artworks similar and fit with your style.

I understand that you have requested a third image, so I'll ask you to confirm the style of these two images and I will be happy to provide a proposal for this today.

Image 1: Fushuma On-chain Democracy
The sages sit in a circle and examine the proposals.
![Democracy](https://github.com/Fushuma/Dev_grants/assets/169058859/e2b699cf-3847-4a18-900a-429efa1c4e79)

Image 2: Rise Of Democracy
Samourai watching the sun rising, ready for a new day, a new hope.
![Rise](https://github.com/Fushuma/Dev_grants/assets/169058859/871057b8-0ca6-46a4-9192-cf2c695524dd)

**Comment by WhyNt2024** [comment]
I came with that for the Dojo. On the wall you can read "Dojo" and " persistence is the father of success" in Japanese, next to the fushuma logo

![Dojo](https://github.com/Fushuma/Dev_grants/assets/169058859/ac2a8d77-f0ba-48ae-90eb-724e535e8a3a)

**Comment by spatialiste** [comment]
Hello @WhyNt2024 these pictures are approved, the style fits very well with Fushuma.
I will do some tests and tell you if any change is necessary.

**Comment by spatialiste** [comment]
> I came with that for the Dojo. On the wall you can read "Dojo" and " persistence is the father of success" in Japanese, next to the fushuma logo
> 
> ![Dojo](https://github.com/Fushuma/Dev_grants/assets/169058859/ac2a8d77-f0ba-48ae-90eb-724e535e8a3a)
> 

So, no need for any changes, everything's great, thank you.

Can you please let me know the amount you're requesting for the three images? Also, provide me with your cryptocurrency wallet address so we can send the payment promptly. Thanks!

**Comment by WhyNt2024** [comment]
For making these 3 pictures I request 185 USD.

Total amount requested: 185 USDT.
BEP 20 USDT Payment address: 0x1c9fa15bec327d0c0b47bc37168dee353067a89f
Thank you.

**Comment by spatialiste** [comment]
Hello, the payment has been processed, and this grant is now closed.

Transaction link:
https://bscscan.com/tx/0x784877505463bbcbf56325114773cf9b6e17f703cea01d7cd2859f39f5812e87

Thanks again for your contribution!

**Comment by spatialiste** [comment]
Hello, the payment has been processed, and this grant is now closed.

Transaction link:
https://bscscan.com/tx/0x784877505463bbcbf56325114773cf9b6e17f703cea01d7cd2859f39f5812e87

Thanks again for your contribution!
