### ISSUE TITLE
Klikr

### ISSUE THREAD

**Issue by adamblockcz** [Fushuma/Dev_grants#13]
**Project Title:**
- Klirk

**Applicant Information:**
- **Name:** Adam Zelfel
- **Contact Email:** adam@blockczech.io
- **GitHub or relevant online profiles:** https://www.linkedin.com/in/adam-zelfel-21159a19a/
- **Team Members (if applicable):** Ondrej Vomela, Jakub Strnad

**Project Overview:**
- **Summary:** Klirk is a community engagement and marketing tool fostering community growth and activity. Inspired by the famous clicker games it entertains users and allows them to compete for different prizes. Inviting friends and sharing content is the essence of Klikr. Currently Klikr is implemented as a telegram web application and bot that connects into your community. In Klikr projects can get their own custom branded space and settings.
- **Goals:** We aim to grow our community into a million active users as well as set the current trend for engaging marketing.
- **Impact:** Any project or ecosystem can achieve their own goals with Klikr. Klikr incentivizes users and community member to fullfil several tasks and play the game in order to win the project's prize. That can be tokens, cash prize, access to whitelist and basically anything that can bring value to motivated community. Community can enjoy fun competing for the prizes and grow itself via sharing.

**Technical Details:**
- **Technology stack:** AWS, Fastify, Django, Redis, AWS, Postgres
- **Project roadmap:** Growing community into 1 mil active users - in following 4 months.
- **Current state:** Current state is 115k registered users of which around 75% are MAU.

**Funding:**
- **Total amount requested:** 40,000 USD in Fuma
- **Budget breakdown:** 
15.000 - LP
10.000 - prize pools
10.000 - marketing in app
5.000 - Memecoin launch

- **Payment address:** 0xf53AceBfb776beb0cF6Bb0adabfd82b3dcC79a90

**Additional Information:**
- **Previous work:** https://tcg.world, X.LA, https://efkplatform.com/
- **How did you hear about our grants program?:** From a friend

**Declaration:**
I hereby declare that all information provided is true and accurate to the best of my knowledge.

- Adam Zelfel
- 10.6. 2024

---

Please submit this application by creating a new file in the [GitHub repository's](URL-to-application-submission-repository) `applications` directory and opening a Pull Request for review.

**Comment by spatialiste** [comment]
Hello Adam,

Thank you for submitting your proposal. The concept of Klirk is interesting, and we’ve been closely following the "tap to earn" trend. However, it appears that this trend alone may no longer be enough to attract users. The idea would need to be coupled with additional features to stand out.

At this time, as the Fushuma blockchain has not yet launched, so I'm closing this grant for now. You’re welcome to reapply with an updated proposal once the blockchain is live.

Thanks again for your interest, and we look forward to hearing from you in the future!
