### ISSUE TITLE
Fushuma Website Pictures #2

### ISSUE THREAD

**Issue by spatialiste** [Fushuma/Dev_grants#14]
# Designer Grants Application

Fushuma is looking for talented and imaginative designers to create engaging images in the Fushuma style for our website.
The idea is to let designers propose their vision of Fushuma and the proposed themes. The descriptions are concise on purpose.

- **Image 1:**  Bridges to Legacy

An image representing/symbolizing the transition from Callisto Network to Fushuma, towards new horizons.

----

### Design Style Guide:
We are looking for designs in a Japanese old style— clean, and 2D. Technical representations are to be avoided, and symbolism is appreciated.

### Below are some Fushuma images for your reference:

**The Fushuma Logo**

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/57f06cf5-de2c-40a7-b9f2-266262619d36)

**Latest Creations**
![image](https://github.com/Fushuma/Dev_grants/assets/41175366/bb5a5393-064e-4ecd-9bf0-698a317c300c)

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/58f13161-a5e5-42d6-9e16-3d2bb21dba27)

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/e4399d2b-4628-465f-acca-194f216819f2)

-----
### Application Submission Requirements:
- **Proposed Timeline:** [The time you need to complete these designs]
- **Total amount requested:** [Amount in USDT]
- **Payment address:** [Cryptocurrency address for receiving funds]

**Comment by pKosRed** [comment]
Hello!
I managed to overcome the technical problems.

I am sending the graphic that you currently need.
It directly symbolizes the bridge and the passage to Fushuma.

Additionally, due to technical problems with creating an account (no email confirming registration), I could not submit my already completed works for the grant. For this reason, I am attaching them here - maybe something will be useful and the work will not go to waste.

For the graphic for the current grant, due to the complexity of the activities, $60 - $70 will be fine. 
For the previous graphics, despite the time invested in their implementation, $50 for one or $75 for all 3.

![legacy (1)](https://github.com/Fushuma/Dev_grants/assets/173097086/77a1bb21-4e12-456d-9a1a-9b0f40ffc6b1)
![legacy](https://github.com/Fushuma/Dev_grants/assets/173097086/2c157f7f-fd54-42a3-ac59-4b6eeaa685fc)

Current needed graphics in 2 versions with and without the fushuma font. Of course I will send them for editing in PSD.

Previous grant graphics below:
![chain](https://github.com/Fushuma/Dev_grants/assets/173097086/688adcf1-0216-4149-bd9c-3243e53c18e0)
![Dojo_Learning](https://github.com/Fushuma/Dev_grants/assets/173097086/fdb39640-4be2-4108-8466-eaa87800f7ec)
![Democracy](https://github.com/Fushuma/Dev_grants/assets/173097086/52bcd8a7-c950-4bda-baa9-f8ed8c89eb99)

Size of all file: 1600x900px, 72dpi.

Thank you.

**Comment by spatialiste** [comment]
Hello @pKosRed glad that you solved the Github verification process.

Honestly, I love the concept of the image you are submitting, and it is definitely in the style of Fushuma, congratulations. However, I'm afraid that it looks too much "AI". The use of AI is OK but in that case, there are some issues that need to be fixzs. Let me show you:

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/065c7b32-1e5c-415d-8b9a-4a6a587a8fc1)

1. The white part in the sun, I think we should rather have a complete sun.
2. The small bridge, it looks like to going nowhere, so I'm not sure maybe better to remove it.
3. The element under the bridge looks incomplete.
4. We should probably remove the partial elements on the sides.
5. We usually place the logo in the bottom right, so having a space for it would help a lot.

In general, having the pictures without text is probably better.

If you can fix the points mentioned, I believe that we can allocate the requested budget. Maybe creating other options could be a good idea so we can choose the best one.

As for your previous work, the grants are completed but I really like this picture, so I will think how we could use it.

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/29fee6ff-69d5-4162-825a-eaad32da035e)

**Comment by pKosRed** [comment]
I fixed the errors you asked for.

The image was composed of 3 different images, the background was scaled to a higher resolution and I didn't notice that it was generated with the elements left - sorry.

I didn't make an additional image, it would take a lot of time. If you reject this image for some reason I can make a new one. I'm uploading the full resolution image both images.

![legacy (4)](https://github.com/Fushuma/Dev_grants/assets/173097086/39fe4a66-37de-4229-a366-f2e7a047d198)
![Dojo_Learning](https://github.com/Fushuma/Dev_grants/assets/173097086/2efced2d-65c7-4263-9f6c-83f3f9352f8c)

**Comment by spatialiste** [comment]
Hey, thank you. The picture is better yes, but now there are new issues. 

1. Part of the house is missing.
2. There is a grey element on the trees.

Honestly, I don't like the green elements in the bottoms they don't match the look and feel of the picture. I would simply remove them. Maybe some watercolor paint effects like the pictures I put in reference? 

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/81827098-92cf-4d44-9eef-5bb0f90853ac)

**Comment by pKosRed** [comment]
Watercolor in this style? The entire image is repainted, then the edges are adjusted to match the bottom composition
![legacy_v2](https://github.com/Fushuma/Dev_grants/assets/173097086/41e18783-360a-472d-9683-7086803a6860)

**Comment by pKosRed** [comment]
![Uploading legacy_v2.png…]()

**Comment by WhyNt2024** [comment]
I am submitting 1 image for the grant. I used the beige and red colors for the new horizons, and gray for the other side of the bridge. The people are walking towards the east, where the sun rises. The right side is empty to allow for the logo. If you like this picture I'd be happy with 50 USD.

BEP 20 USDT Payment address: 0x1c9fa15bec327d0c0b47bc37168dee353067a89f
![Bridges-to-Legacy](https://github.com/Fushuma/Dev_grants/assets/169058859/84923ba2-286c-48c0-b763-e14203a2f7ff)

**Comment by spatialiste** [comment]
Thank you guys, I will review both options with the team and will get back to you.

**Comment by TomasGrap** [comment]
Hello!
This is my proposal, I send in low resolution if I choose to send in high resolution.

Thanks.

![IMG_2910](https://github.com/Fushuma/Dev_grants/assets/173384425/33bb4efd-462c-4500-bce0-d4cba429b7a7)

**Comment by spatialiste** [comment]
> Hello! This is my proposal, I send in low resolution if I choose to send in high resolution.
> 
> Thanks.
> 
> ![IMG_2910](https://private-user-images.githubusercontent.com/173384425/341465999-33bb4efd-462c-4500-bce0-d4cba429b7a7.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4OTY1ODMsIm5iZiI6MTcxODg5NjI4MywicGF0aCI6Ii8xNzMzODQ0MjUvMzQxNDY1OTk5LTMzYmI0ZWZkLTQ2MmMtNDUwMC1iY2UwLWQ0Y2JhNDI5YjdhNy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjBUMTUxMTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmQzMzYwYzkzM2E5YzBjODA3NDUyOGZkNzBlZGRkYzA1MTcyOTQwZDFhYWVmYTdjMDFiZTVjMjQyMTBiYTBmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vbyHMCC3PdLBlOIyveHZo-0PK-XDIVK60s07A-E9AAs)

This is also a great proposal, thank you, let me check with the team.

**Comment by TomasGrap** [comment]
Hello,
When can we expect an answer?

**Comment by spatialiste** [comment]
Hello everyone, and apologies for the delay, as we have had many tasks to handle recently.

All the submissions were great so it was hard to decide, but after careful consideration of the current Fushuma style, we have decided that the proposal by @WhyNt2024 aligns best.

The screenshot below is taken from the Fushuma blog page. It represents the current visual style and what we should aim for when creating the designs.

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/d617df50-2889-4f8a-a590-9c862f7df3fc)

For future designer grants, we will provide guidelines to represent the Fushuma style more accurately without being too restrictive. These will serve as references rather than strict rules.

- **Style**: Japanese old style— clean, and 2D. Technical representations are to be avoided, and symbolism is appreciated
- **Color Palette**: Use shades of beiges, browns, reds, and blacks. Other colors should be subtle.
- **Composition**: Harmonious, without excessive detail.
- **Logo Space**: Reserve space at the bottom right for the Fushuma logo.

We appreciate all of your contributions to this grant and recognize that @pKosRed and @TomasGrap have provided inputs that will help improve the description of upcoming designer grants. Therefore, we are awarding them a special grant of $20 each.

@pKosRed, @TomasGrap please submit your BEP20 wallet so we can transfer your grant.

Thanks to everyone.

**Comment by TomasGrap** [comment]
Thank you, 
Address on BEP20: 0x33B9CF4183917172e7c53F77c7416B1d77D0632e.

**Comment by pkosred1** [comment]
Thank you for recognising my work 🙂

I have a problem logging in to my account due to email authorisation of access. I contacted about problems with the account - now there will be no problems.

BEP20
0xaEd5f9E809CC9f872cCA880A80Fa0F3d01B4F368

Thank you.

**Comment by TomasGrap** [comment]
Is another grant for graphics or video planned? @spatialiste

**Comment by spatialiste** [comment]
Hello guys,

We processed the payments for this grant this morning, please find the transactions below:

- @WhyNt2024: https://bscscan.com/tx/0x6fe218805bb5afccc96afd6bd921e7ee34fd570833d4eba0b8612a8ec1a997a6
- @pKosRed: https://bscscan.com/tx/0x0cefeda8673c530a153297d64f5611f86b17227ad18286f71eaff39e19a04078
- @TomasGrap: https://bscscan.com/tx/0x2e18f4889536dd422d0a33d47f8ee6cbe3820ccabd4d114f05ea035f92131de6

Yes @TomasGrap we will have more designer grants in the future, so I suggest you follow the Fushuma Github account so you will be notified when new grants are open.

I'm closing this grant as it is now completed. Thanks again for your contributions guys!

**Comment by spatialiste** [comment]
Hello @pKosRed / @pkosred1

I want to inform you that we have utilized the image you created in the previous grant in today's article. We have completed the processing for the transfer of 50 USD:

https://bscscan.com/tx/0x969ecb1eebc5539d3c50c641bfbcf1625668ed83849ce44ef0e19fc9b062189e

Link to the publication:
https://fushuma.com/fushuma-blockchain-infrastructure-partnerships/

Thank you for your work and support, have a great weekend!

![image](https://github.com/user-attachments/assets/b58c8fa5-f1a5-4507-864d-507a3a920efe)
