### ISSUE TITLE
Community Tutorial Grant #1

### ISSUE THREAD

**Issue by spatialiste** [Fushuma/Dev_grants#15]
# **Community Tutorial Grant Application**

Fushuma invites the community to create a comprehensive tutorial on **migrating CLO or CLOE to CE**. We’re offering **$150 USD in FUMA tokens** to the author of the most clear, concise, and engaging tutorial that helps users transition smoothly.

### **Tutorial Theme:**

- **Tutorial Topic:** *How to Migrate CLO or CLOE to CE*

Your tutorial should clearly explain the steps for users to migrate CLO or CLOE tokens to CE. The content should be easy to follow, with a focus on clarity and user-friendliness.

### **Tutorial Style Guide:**

- **Format:** Written guide supplemented with screenshots.
- **Structure:** Step-by-step instructions with clear headings and subheadings.

### **Evaluation Criteria:**

- **Clarity:** Is the tutorial easy to follow and understand?
- **Comprehensiveness:** Does it cover all necessary steps and details?
- **Engagement:** Is the tutorial engaging and well-structured?

----

### **Submission Requirements:**

- **Proposed Timeline:** [The estimated time needed to complete the tutorial]
- **Total Amount Requested:** $150 USD (paid in FUMA tokens)
- **Payment Address:** [Your cryptocurrency address for receiving FUMA tokens]

**Comment by davhzeus** [comment]
Hello team.
I'd like to work on a guide for migrating from CLO and CLOE to CE.

I will submit my proposal no later than Thursday, June 20, 2024 at 18:00 GMT.

**Comment by davhzeus** [comment]
Tutorial on how to migrate from CLO and CLOE to CE.

**French version**
[FR_Migration de CLO_CLOE vers CE.pdf](https://github.com/user-attachments/files/15937166/FR_Migration.de.CLO_CLOE.vers.CE.pdf)

**English version**
[EN_Migrating from CLO_CLOE to CE.pdf](https://github.com/user-attachments/files/15937167/EN_Migrating.from.CLO_CLOE.to.CE.pdf)

**Comment by spatialiste** [comment]
Hello @davhzeus, first of all, thank you for applying.

We have reviewed your files and they are approved, please submit your wallet address and we will send you the FUMA tokens 7 days after the trading starts.

(For the wallet, you can provide your current CLO wallet, since Fushuma will be EVM compatible).

**Comment by davhzeus** [comment]
Hell @spatialiste Thanks for the feedback.
Here is my CLO address.

0x7F157B8918aa9Ff6ef8BB2f6242871B5e6d79898

Best regards.

**Comment by spatialiste** [comment]
Thank you @davhzeus, this grant is now completed so I am closing it.
