### ISSUE TITLE
Fashuma Expansion/Development/Hackathon

### ISSUE THREAD

**Issue by MartinMwendasatoshi** [Fushuma/Dev_grants#18]
Project Title:
**Fashuma Expansion/Development/Hackathon**

Applicant Information:

Name: 
Mumocrypto 
Martinmediax- founder of https://kenyablockchainandcryptoconference.co.ke/  and CMO at Mediax
Lewis- event organizer at https://kenyablockchainandcryptoconference.co.ke/ 

Contact Email: marketing@mediax.agency

Relevant online profiles:

Twitter:[ https://x.com/mumo_mumo](https://x.com/mumo_mumo)_
YouTube:[ https://www.youtube.com/@mumo](https://www.youtube.com/@mumo)
TikTok: http://tiktok.com/mumo_mumo_
https://kenyablockchainandcryptoconference.co.ke/

**Team Members:**

Mumocrypto and Martinmediax
Role: Team Leaders
Telegram ID-https://t.me/MartinmediaX 

Lewis Guantai
LinkedIn:[ http://linkedin.com/in/lewis-guantai-34a165250](http://linkedin.com/in/lewis-guantai-34a165250)
Telegram ID: @Guantailewis

Martinmediax- founder of https://kenyablockchainandcryptoconference.co.ke/  and CMO 

**Project Overview:**

Summary: The Fashuma Expansion/Development/Hackathon project aims to significantly enhance the Fashuma ecosystem by organizing a comprehensive campus tour, educational workshops, and a hackathon event across five major universities in Kenya. The initiative is designed to engage developers and students, foster innovation, and accelerate project development within the Fashuma ecosystem.

**Goals:**

Expand the Fashuma community locally through targeted educational initiatives.
Engage developers and students in hands-on workshops and hackathons.
Facilitate the development and deployment of innovative projects within the Fashuma ecosystem.
Impact: The project is expected to engage 900 developers and enthusiasts, generate 200 project ideas, and advance 60 projects to a hackathon event with 300 developers. From the hackathon, 15 projects will proceed to a one-month acceleration program, with an estimated 11 projects successfully deploying on the Fashuma platform. This will provide valuable tools, mentorship, and experience for participants to create impactful blockchain-based solutions.

**Technical Details:**

Technology stack:
Fashuma platform and tools
Blockchain technology
Decentralized application (dApp) development frameworks
Security and scalability solutions

**Project roadmap:**

Campus Tour (3 weeks)
Start Date: September week 1
End Date: September week 3

Conduct workshops at five universities, covering topics such as Fashuma tools, blockchain fundamentals, and project development.
Hackerhouse Event (3 days)
Start Date: September dy 1
End Date: September dy 3

Intensive development environment for selected teams with continuous mentorship.

Acceleration Program (1 month)
Start Date: week 1
End Date: week 4

Advanced mentorship and workshops to refine and scale the top 15 projects.

Current state: The Fashuma platform is established, and the community is actively engaged. The proposed expansion will build on existing momentum to broaden the developer base and foster new projects.

**Funding**:

Total amount requested: $16,840 + $7,490 for PR distribution via MediaX - our partnered PR distribution agency.
 
Budget breakdown:
Venue: $2,200
Refreshments: $1,500
Educators: $2,400
Power Supply & Internet: $500
Photography: $1,000
Promotion: $300
Hackathon Prize: $4,000
Mentors Compensation: $1,440
Core Team Compensation: $2,000
Event Operations: $1,500
Scale 300+ Guaranteed Published PRs: $7,490 for extensive press release distribution through [MediaX](https://mediax.agency/submit-press-release).

Payment address: [0x6f14234bf66291c9142b09D187ECFA41422486aA]

**Additional Information:**

Previous work:Code Africa Event: Organized in partnership with KBCC (https://kenyablockchainandcryptoconference.co.ke/), held from 6th to 11th May, 2024. (codeafrica.xyz)

Internal Virtual Bootcamps: Hosted multiple virtual bootcamps to train developers in blockchain technologies.

How did you hear about our grants program?: [from Github community]

Declaration: I hereby declare that all information provided is true and accurate to the best of my knowledge.

**Comment by spatialiste** [comment]
Thank you for your proposal.

After reviewing it, we believe that, for now, it will be more beneficial to focus on building and establishing the online community via social media platforms. Once we’ve solidified our presence there, we’ll shift our focus to IRL events, which are definitely a part of our long-term strategy.

We appreciate your understanding and look forward to future collaborations!
