### ISSUE TITLE
Logo for Fushuma

### ISSUE THREAD

**Issue by creepas** [Fushuma/Dev_grants#2]
Grant Proposal: Logo for Fushuma
Basic Style of the design of logo should be "Japanese anime" modern clean 2D style. With futuristic parts connected to blockchain technology and AI.. Please submit your budget request.

Project Title:

Logo for Fushuma
Applicant Information:

Name: [Applicant's Name]
Contact Email: [Applicant's Email]
GitHub or relevant online profiles: [GitHub Profile/Portfolio]
Team Members (if applicable): [List team members]
Project Overview:

Summary: Design a unique logo for Fushuma
Goals: Create a visually appealing logo 
Impact: Enhance brand visibility and user engagement for the ICO.
Technical Details:

Funding (example only):

Total amount requested: $X
Budget breakdown: $Y
Payment address: [Cryptocurrency Address]
Additional Information:

Previous work: [Links to previous design projects]
How did you hear about our grants program?: [Source]
Declaration:
I declare that the information provided is accurate to the best of my knowledge.

[Applicant's Name]
[Date]
Submit this application by replying.

**Comment by wink2w** [comment]
Here are demo logos.
Looking forward to feedback

**Comment by wink2w** [comment]
![50](https://github.com/Fushuma/Dev_grants/assets/88339871/8ecc0dd4-a9c7-48a7-94d0-3c1af71f1fb5)
![51](https://github.com/Fushuma/Dev_grants/assets/88339871/44d8b1f8-ce0b-42b7-aaac-c42057f28694)

**Comment by spatialiste** [comment]
Could we try your last proposal with the ' 襖 ' kanji?

> ![50](https://private-user-images.githubusercontent.com/88339871/312650111-8ecc0dd4-a9c7-48a7-94d0-3c1af71f1fb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDA5NTAsIm5iZiI6MTcxMDQ0MDY1MCwicGF0aCI6Ii84ODMzOTg3MS8zMTI2NTAxMTEtOGVjYzBkZDQtYTljNy00OGE3LTk0ZDAtM2MxYWY3MWYxZmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE4MjQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMzdhOTBlMTVmOWY5NjY4NjIxMjE0MWM0MTE0ZjJmYTAxYzVkNTYyMWYxZTcyY2ExZjI0ZTEzZmY1NDMzNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pW2RafFHArj0q-YjxFZuAFVxcthzHsgnCgbALLRX3k4) ![51](https://private-user-images.githubusercontent.com/88339871/312650117-44d8b1f8-ce0b-42b7-aaac-c42057f28694.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDA5NTAsIm5iZiI6MTcxMDQ0MDY1MCwicGF0aCI6Ii84ODMzOTg3MS8zMTI2NTAxMTctNDRkOGIxZjgtY2UwYi00MmI3LWFhYWMtYzQyMDU3ZjI4Njk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE4MjQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZjU0YTA3ZTg4NzViY2Q4NzU4ZDYwMjYzNzE3OTZjOTEwNzMxODBjZGNlNDc5OGYwYzI4Nzg2NDhmM2M3YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.86i9QYZD52Qexzvpp6hnptp83m5u87ALjXpb4PZ31rs)

**Comment by PrinceKAlgorithmXpert** [comment]
Yes, we can.

**Comment by PrinceKAlgorithmXpert** [comment]
@spatialiste  Then give me the name of the hieroglyph, I can’t understand exactly what it is. Very small details, you can make a mistake and there will be a completely different meaning. 
I could be wrong and there will be a completely different meaning You understand

**Comment by spatialiste** [comment]
This means 'Fusuma' in japanese. I have attached a screenshot and a link if
it can help.

http://en.ikanji.jp/character/%E8%A5%96

**Comment by PrinceKAlgorithmXpert** [comment]
![51-1](https://github.com/Fushuma/Dev_grants/assets/88339871/34ff4e07-efdb-45e7-9c13-da491fd5807f)
![51-2](https://github.com/Fushuma/Dev_grants/assets/88339871/6594e598-cf1a-4e25-9259-86d283d6b19e)
![52-1](https://github.com/Fushuma/Dev_grants/assets/88339871/68555792-49f7-4548-a10f-7f557f3cb480)
![52-2](https://github.com/Fushuma/Dev_grants/assets/88339871/51cafc93-7ce8-4a51-8763-4663275d25c9)

**Comment by PrinceKAlgorithmXpert** [comment]
@spatialiste, changed it,
please give me  your feedback

**Comment by NadiaUdv** [comment]
Hello, I have prepared three logo options
- with a dragon
- with koi fish
- with fusuma
![Logo_Fushuma_dragon](https://github.com/Fushuma/Dev_grants/assets/60670781/64796b08-bdef-48b2-b870-71d9db7e0810)
![Logo_Fushuma_koi](https://github.com/Fushuma/Dev_grants/assets/60670781/5a0f95b2-292c-463f-8a5e-43cbf9fc0995)
![Logo_Fushuma_fusuma](https://github.com/Fushuma/Dev_grants/assets/60670781/b9f85e9e-efb1-4866-8568-18907eeb7907)

**Comment by NadiaUdv** [comment]
Here is the animation for the logo with fusuma
![Fushuma](https://github.com/Fushuma/Dev_grants/assets/60670781/aae6b5c0-9e01-4d21-9686-94d207a5bfd8)

**Comment by spatialiste** [comment]
Thanks a lot Nadia. I will discuss it with the team on Monday and will get back to you.

**Comment by spatialiste** [comment]
**We're excited to announce the results of the Fushuma logo grant proposal! A huge thank you to @wink2w and @NadiaUdv for your amazing submissions.**

Congratulations to @NadiaUdv, your logo design has been selected! Please send us your requested payment amount and wallet address, and we will proceed with the transaction tomorrow.

Thank you both for contributing your talents to the Fushuma community!

**This grant is now closed!**

**Comment by NadiaUdv** [comment]
@spatialiste Thank you, I hope my logo will bring success to your project!

I spent about 8 hours creating 3 logo options
An hour of my work costs $16

So price logo $16x8h = 128 USDT(BEP-20)

Here is my wallet address:
0x76c04af8446b788918e0200997245732ba6d0408

**Comment by spatialiste** [comment]
Thanks again, Nadia!
On our side, we have processed the payment; below is the transaction.

https://bscscan.com/tx/0xe20b5075585e6ff6e813b5fa982c8ac822e340ce43a0dba3c2c93ad151f344f7
