### ISSUE TITLE
Integration of Uniswap V3 protocol into Sloth Finance UI

### ISSUE THREAD

**Issue by yuriy77k** [Fushuma/Dev_grants#3]
# Development Grant:  Integrate Uniswap V3 protocol in Sloth Finance UI

## Technical Details:

1. Fork/create Uniswap V3 router and integrate it in Sloth Finance UI
2. Update UI accordingly changes in V3 compared to V2 (update swapping options, add/remove liquidity process).
3. Implement interaction with a fork of Uniswap V3 smart contracts.

- **Technology stack:** Javascript, React, Subgraph
- **Current state:** https://app.soy.finance/en/swap
- Source code of Sloth Finance UI: https://github.com/CallistoEnterprise/soy-finance-app-v2

**Comment by spatialiste** [comment]
This grant has been replaced by a revised grant. Please find the updated details here: [Link](https://github.com/Fushuma/Dev_grants/issues/17).
