### ISSUE TITLE
3d Animated Sting Logo

### ISSUE THREAD

**Issue by NTZD** [Fushuma/Dev_grants#5]
# Development Grants Application Template

**Project Title:**
- Create a 3d animated sting of the Fushuma logo. This will serve as part of the landing page of the website and also a quick opening for videos on social media platforms. 

**Applicant Information:**
- **Name:**
- **Contact Email:**
- **GitHub or relevant online profiles:**
- **Team Members (if applicable):**

**Project Overview:**
- **Summary:** [Brief description of your project]
- **Goals:** [What you aim to achieve with this project]
- **Impact:** [How your project will benefit the ecosystem or community]

**Technical Details:**
- **Technology stack:** [Technologies to be used]
- **Project roadmap:** [Key milestones and estimated completion dates]
- **Current state:** [Any work already done]

**Funding:**
- **Total amount requested:** [Amount in cryptocurrency]
- **Budget breakdown:** [Detailed budget allocation for different aspects of the project]
- **Payment address:** [Cryptocurrency address for receiving funds]

**Additional Information:**
- **Previous work:** [Link to any previous projects or contributions]
- **How did you hear about our grants program?:**

**Declaration:**
I hereby declare that all information provided is true and accurate to the best of my knowledge.

- [Applicant's Name]
- [Date]

---

Please submit this application by creating a new file in the [GitHub repository's](URL-to-application-submission-repository) `applications` directory and opening a Pull Request for review.

**Comment by LHMGMY** [comment]
Hi there, I have prepared an animation with SFX based on the fushuma animated logo that won the [logo grant](https://github.com/Fushuma/Dev_grants/issues/2).

https://github.com/Fushuma/Dev_grants/assets/165788217/3e68c6cb-21e2-4a7c-ac74-a585afc8ed97

Waiting for comments.

**Comment by spatialiste** [comment]
Hi, that looks amazing! Could you please tell us the price to produce this animation?

I have a question: is it easily customizable? If yes, then it's amazing, and I would ask you to send me the elements via Telegram https://t.me/TontonBenz.

Another point is, can we create a banner for our Twitter account based on it? The size should be 1500×500 pixels.

**Comment by LHMGMY** [comment]
Glad you like it :) As we discussed in Telegram, the price for the animation and assets is $500, and I'm preparing the Twitter banner for $50.

Please send USDT payment to my Tron wallet: TTU97Tpugf4qScnFBAzdk8ZbrggPzYrg3G

**Comment by spatialiste** [comment]
Actually, we love it! Gerhard has already tweaked it and we've published an animation based on your template.

I just made the payment for the video, thank you for your contribution!

Tx hash: https://tronscan.org/#/transaction/29f8ad3d4f2588a57cb557bfe6601a7661b862e7b1533858fd3eb8a2e2aa7abf

**Comment by LHMGMY** [comment]
Hi, I have prepared a Twitter banner mixing elements and inserting the dragon you used in your [published](https://twitter.com/i/status/1775207472728297511) animation.

![Fushuma twitter banner](https://github.com/Fushuma/Dev_grants/assets/165788217/3434b5be-ac9b-42a8-bbf5-c47e133eb792)

Waiting for comments.

**Comment by spatialiste** [comment]
I like it a lot, congratulations! I will share it with the team but I guess we will go with it!

**Comment by spatialiste** [comment]
The Banner was approved, and payment was processed; thank you!

Tx hash: https://tronscan.org/#/transaction/452abb025c39ee8c53e5b3f1c69bd93f2c44d8d3e6ee8cc215d60dd16923f8a1
