### ISSUE TITLE
Twitter Banner & Announcement Template

### ISSUE THREAD

**Issue by spatialiste** [Fushuma/Dev_grants#6]
# Designer Grants Application Template

Following the successful creation of our logo, we're excited to announce a new grant opportunity for designers!

This time, we call to your talent to design:

- **A Twitter Banner for Fushuma:** This banner should encapsulate the essence of Fushuma, reflecting our commitment to security, innovation, and community engagement.

 - **An Announcement Image for Fushuma:** We need a versatile image template that can be customized with different text titles and background adjustments according to the news. This image should align with Fushuma’s branding and be adaptable for various announcements.

### Design Style Guide:
For both items, we are looking for designs in a Japanese anime style—modern, clean, and 2D, with futuristic elements related to blockchain technology and AI.
 
Note: Please provide multiple design options for each request.

### Below is the approved Fushuma logo for your reference:
![image](https://github.com/Fushuma/Dev_grants/assets/41175366/5276d828-00fe-4c4c-a90c-0af4be7140dc)

---
### **Application Submission Requirements:**

- **Proposed Timeline:** [The time you need to complete these designs]
- **Total amount requested:** [Amount in USDT]
- **Payment address:** [Cryptocurrency address for receiving funds]

**Comment by NadiaUdv** [comment]
Hello, I have prepared three banner options.

In each banner you can change the title, subtitle and key image depending on the news. As an example, I showed news about blockchain integration.

![banner_1_1600x900](https://github.com/Fushuma/Dev_grants/assets/60670781/81c50645-ebf3-4d29-8b13-54186dbdd887)
![banner_2_1600x900](https://github.com/Fushuma/Dev_grants/assets/60670781/497c0ab9-aa3e-4495-887a-83b7a8c1e9c2)
![banner_3_1600x900](https://github.com/Fushuma/Dev_grants/assets/60670781/10d6d03a-0e20-4369-b15e-f7b60975a98e)

**Comment by spatialiste** [comment]
Hi Nadia, I apologize for the late reply; last week was busy...

Thanks for your contribution. I'm afraid they look too complex. Perhaps it would be worth reviewing the style proposed for the animation that was submitted? Please review it [here](https://private-user-images.githubusercontent.com/165788217/318767175-3e68c6cb-21e2-4a7c-ac74-a585afc8ed97.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjgzMzIsIm5iZiI6MTcxMjA2ODAzMiwicGF0aCI6Ii8xNjU3ODgyMTcvMzE4NzY3MTc1LTNlNjhjNmNiLTIxZTItNGE3Yy1hYzc0LWE1ODVhZmM4ZWQ5Ny5tcDQ_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQxNDI3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzJkMDRmODZlMTk3ZTQwMjI5ZmQyNjNlMTMxNjgyNzY4ZGVjYTZlZTEyYWY2M2IxMDkxMWJkMjE4MTNiZjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q6d-F03YbzVzdmfY9c5lFhL776nhl5XZJwnnPDe7dVk) and let us know.

**Comment by NadiaUdv** [comment]
@spatialiste Hello, I prepared a new banner in the style of animation

We can make logos and images in the news black so that they fit better into our style

Showed the Fuse Network logo as an example

![banner_1600x900](https://github.com/Fushuma/Dev_grants/assets/60670781/aa354651-1089-409e-9cfa-6a728473785c)

**Comment by spatialiste** [comment]
Hey Nadia, yes, I think this is exactly in the style, well done! We could maybe remove the door in the bottom left and move the logo there?

Also, is it available in PSD format for editing?

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/663720bc-4f14-421e-8783-a7be697832ae)

**Comment by NadiaUdv** [comment]
@spatialiste I updated banner 
 I can't send PSD file here because github doesn't allow me to send this format. I sent you in Telegram
![banner_1600x900](https://github.com/Fushuma/Dev_grants/assets/60670781/5232024d-bb4c-44e9-9907-eda3bef1df71)

**Comment by spatialiste** [comment]
> @spatialiste I updated banner I can't send PSD file here because github doesn't allow me to send this format. I sent you in Telegram ![banner_1600x900](https://private-user-images.githubusercontent.com/60670781/319627089-5232024d-bb4c-44e9-9907-eda3bef1df71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzMwODEsIm5iZiI6MTcxMjMzMjc4MSwicGF0aCI6Ii82MDY3MDc4MS8zMTk2MjcwODktNTIzMjAyNGQtYmI0Yy00NGU5LTk5MDctZWRhM2JlZjFkZjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE1NTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZTRmODA0MGNjYjQ4ZDA4MmRhMDBhYmZjODI4M2VkODE1NjQxZjEwMmExODRjYTE1NWJkYWNmMzYwZmQzMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qdWYnceShu4eMmKU8tijMh1Y1fkbYoXvj3zAi9VUq7w)

Yes! I like this structure, and the fusuma background behind the logo is really nice.

I have received the PSD, so please tell me the cost of this task so I can proceed with the payment.

Also, could you please export the third option in PSD, we could eventually rework it.

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/c3ae066c-cbfb-4a3f-9092-e20772ff4b40)

 Thanks a lot, Nadia. :)

**Comment by NadiaUdv** [comment]
@spatialiste Thank you, I sent you in Telegram PSD file with the third version of the banner. 

Preparing of 4 banners options took about 9 hours my work time.

Price $16x9h = 144 USDT(BEP-20)

Here is my wallet address:
0x76c04af8446b788918e0200997245732ba6d0408

**Comment by spatialiste** [comment]
Great, here I just made the payment to your wallet:

https://bscscan.com/tx/0xb80120f93e0ef6fa4a57529f606d5ebcfdc8db0c976036c396a2867fc7756f28

Thanks again, wish you a great weekend.
