### ISSUE TITLE
Fushuma ICO Image Creation Grant

### ISSUE THREAD

**Issue by spatialiste** [Fushuma/Dev_grants#9]
# Designer Grants Application

As we prepare for the launch of our ICO, Fushuma is seeking talented visual artists to create engaging images in the Fushuma style for our ICO page:

- **Image 1: Airdrops from Funded Projects**
This image should depict FUMA token holders receiving airdrops from various funded projects, illustrating the benefits of holding FUMA.

- **Image 2: Tokenomics**
Design a visually appealing pie chart that represents the distribution of FUMA tokens.

### Design Style Guide:

For both items, we are looking for designs in a Japanese anime style—modern, clean, and 2D, with futuristic elements related to blockchain technology and AI.

**Note:** Please provide multiple design options for each request.

### Below are some Fushuma images for your reference:

**The Fushuma Logo**

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/3191d821-a64d-4908-9b06-9d673c3da8a1)

**The Fushuma Announcement Banner**

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/6188b4fe-e477-488d-8c7f-c850b5ae10d0)

**The Fushuma Twitter Banner**

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/009cbcec-1888-4332-8945-0ace4fbce5f2)

-----
### Application Submission Requirements:
- **Proposed Timeline:** [The time you need to complete these designs]
- **Total amount requested:** [Amount in USDT]
- **Payment address:** [Cryptocurrency address for receiving funds]

**Comment by WhyNt2024** [comment]
Hi, I created 2 images in your company's style with watercolor effects to give your brand more personality. I used traditional Japanese artwork to fit with your style.

Image 1: Airdrops from Funded Projects
This image should depict FUMA token holders receiving airdrops from various funded projects, illustrating the benefits of holding FUMA.

I chose the dragon distributing airdrops with a river to fuma holders; they are symbolized by a Japanese house. 

![Airdrop-dragon](https://github.com/Fushuma/Dev_grants/assets/169058859/c38fb0ae-7913-46e7-aef0-410222d41bf5)

Image 2: Tokenomics
Design a visually appealing pie chart that represents the distribution of FUMA tokens.

![Tokenomic](https://github.com/Fushuma/Dev_grants/assets/169058859/984f0b23-1b16-41ce-82ee-4f2a45719fec)

I prepared an original pie chart based on the information of the ICO page. The pie chart has six parts and is not complete to make it appealing and different. If you would like to continue with my proposal, please confirm the information to be shown and I will finalize it.

**Comment by spatialiste** [comment]
Hello @WhyNt2024, thank you for your participation. I reviewed your design with the team, we like the watercolor style, and it is approved. 

About picture 1, could you edit one of these coins so they don't look too similar? The other coins are all different, and they look great.

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/09bb88fc-5697-41bd-91d8-dcec72642b48)

As for the tokenomics picture, you can use the following information:

- 24% - Callisto Network Migration
- 40% - On-Chain Treasury
- 15% - Founders & Partners
- 14% - VCs, Partners & Advisors
- 1% - ICO
- 6% - Airdrops

**Comment by WhyNt2024** [comment]
I've made the changes you requested, so please have a look at them.

![Airdrop-dragon](https://github.com/Fushuma/Dev_grants/assets/169058859/afff739d-81b1-4db8-9516-435d3f977275)

![Tokenomic_01](https://github.com/Fushuma/Dev_grants/assets/169058859/2e3dccb4-38b5-46e6-b8af-6da4367aabcf)

**Comment by spatialiste** [comment]
Great, could you please insert the Fushuma logo in picture 1?

Picture 2, please use the Montserrat font, and edit the text for "FUMA Token Distribution".

**Comment by WhyNt2024** [comment]
Is that what you are looking for?

![Airdrop-dragon 02](https://github.com/Fushuma/Dev_grants/assets/169058859/68eca6d1-eb6e-4c70-be99-e91ddd4c0b42)

![Tokenomic_02](https://github.com/Fushuma/Dev_grants/assets/169058859/89e9619f-b22d-4c07-849a-2bff0b556f26)

**Comment by spatialiste** [comment]
Hello @WhyNt2024, thank you this grant is now closed.

Please send me the requested amount for your work and your wallet address, we will process the payment today.

**Comment by WhyNt2024** [comment]
Hi, I request 150 USD for making these 2 pictures. Thank you.

**Total amount requested:** 150 USDT.
**BEP 20 USDT Payment address:** 0x1c9fa15bec327d0c0b47bc37168dee353067a89f

**Comment by spatialiste** [comment]
Hello @WhyNt2024 payment was made this morning, you can check it [here](https://bscscan.com/tx/0x01c272663a0c8a030ace37c4ac3abb9fac6e233093dd6cb5a9417352d7e2b49e).

Thanks again for your contribution!

**Comment by spatialiste** [comment]
This grant is now closed.
